autenticacao/urls.py
from django.urls import path

from . import views

app_name = 'autenticacao'

urlpatterns = [
    path('registo/', views.registo_view, name="registo"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

bandas/urls.py
from django.urls import path

from . import views

app_name = 'bandas'

urlpatterns = [
    path('', views.index_view, name="bandas_index"),
    path('banda/<int:banda_id>/', views.banda_view, name="banda"),
    path('album/<int:album_id>/', views.album_view, name="album"),
    path('musica/<int:musica_id>/', views.musica_view, name="musica"),
    path('banda/nova', views.nova_banda_view, name="nova_banda"),
    path('banda/<int:banda_id>/edita', views.edita_banda_view,name="edita_banda"),
    path('banda/<int:banda_id>/apaga', views.apaga_banda_view,name="apaga_banda"),
    path('musica/nova', views.nova_musica_view,name="nova_musica"),
    path('musica/<int:musica_id>/edita', views.edita_musica_view,name="edita_musica"),
    path('musica/<int:musica_id>/apaga', views.apaga_musica_view,name="apaga_musica"),
]

ensinosuperior/urls.py
from django.urls import path

from . import views

app_name = 'ensinosuperior'

urlpatterns = [
    path('', views.index_view, name="ensinosuperior_index"),
    path('disciplina/<int:disciplina_id>/', views.disciplina_view, name="disciplina"),
    path('projeto/<int:projeto_id>/', views.projeto_view, name="projeto"),

]

meteo/urls.py
from django.urls import path
from . import views

app_name = 'meteo'

urlpatterns = [
    path('lisboa/', views.tempo_lisboa_view, name='tempo_lisboa'),

]

portfolio/urls.py
from django.urls import path

from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.index_view, name="index"),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('latintext/', include('latintext.urls')),
    path('bandas/', include('bandas.urls')),
    path('praias/', include('praias.urls')),
    path('ensinosuperior/', include('ensinosuperior.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('', include('portfolio.urls')),
    path('meteo/', include('meteo.urls')),

]

portfolio/models.py
from django.db import models

# Create your models here.

portfolio/views.py
from django.shortcuts import render

# Create your views here.

def index_view(request):
    return render(request, "portfolio/index.html")

portfolio/templates/portfolio/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Portfolio</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/landingpage.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Reddit+Mono:wght@200..900&display=swap" rel="stylesheet">
</head>
<body>


<div class = 'home'>
    <header>
        Portfolio
    </header>

    <nav>
        {% if request.user.is_authenticated %}
            User: {{request.user.username}}
            <a href="{% url 'autenticacao:logout' %}"><button>Logout</button></a>
        {% else %}
            <a href="{% url 'autenticacao:login' %}"><button>Login</button></a>
        {% endif %}

        <a href="{% url 'bandas:bandas_index' %}"><button>Bandas</button></a>
        <a href="{% url 'ensinosuperior:ensinosuperior_index' %}"><button>Curso</button></a>
        <a href="{% url 'meteo:tempo_lisboa' %}"><button>Meteo</button></a>

    </nav>

    <main>Bem vindo ao meu website!</main>
    <footer>Website by Miguel</footer>
</div>

</body>

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Portfolio</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/heropage.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Reddit+Mono:wght@200..900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/feef2720be.js" crossorigin="anonymous"></script>
</head>
<body>


<div class = 'home'>
    <header>titulo</header>
    <nav>menu</nav>
    <main>conteudo</main>
    <footer>Website by Miguel</footer>
</div>