autenticacao/urls.py
from django.urls import path

from . import views

app_name = 'autenticacao'

urlpatterns = [
    path('registo/', views.registo_view, name="registo"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

bandas/urls.py
from django.urls import path

from . import views

app_name = 'bandas'

urlpatterns = [
    path('', views.index_view, name="bandas_index"),
    path('banda/<int:banda_id>/', views.banda_view, name="banda"),
    path('album/<int:album_id>/', views.album_view, name="album"),
    path('musica/<int:musica_id>/', views.musica_view, name="musica"),
    path('banda/nova', views.nova_banda_view, name="nova_banda"),
    path('banda/<int:banda_id>/edita', views.edita_banda_view,name="edita_banda"),
    path('banda/<int:banda_id>/apaga', views.apaga_banda_view,name="apaga_banda"),
    path('musica/nova', views.nova_musica_view,name="nova_musica"),
    path('musica/<int:musica_id>/edita', views.edita_musica_view,name="edita_musica"),
    path('musica/<int:musica_id>/apaga', views.apaga_musica_view,name="apaga_musica"),
]

meteo/urls.py
from django.urls import path
from . import views

app_name = 'meteo'

urlpatterns = [
    path('lisboa/', views.tempo_lisboa_view, name='tempo_lisboa'),

]

portfolio/urls.py
from django.urls import path

from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.index_view, name="index"),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('latintext/', include('latintext.urls')),
    path('bandas/', include('bandas.urls')),
    path('praias/', include('praias.urls')),
    path('ensinosuperior/', include('ensinosuperior.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('', include('portfolio.urls')),
    path('meteo/', include('meteo.urls')),

]

bandas/models.py
#bandas models.py
from django.db import models

# Create your models here.

class Banda (models.Model):
    nome = models.CharField(max_length = 100)
    foto = models.ImageField(null = True)
    descricao = models.TextField(blank = True, null = True)
    nacionalidade = models.CharField(max_length = 100, null = True)
    ano_criacao = models.IntegerField(null = True)

    def __str__(self):
        return f'{self.nome}'

class Album (models.Model):
    titulo = models.CharField(max_length = 100)
    capa = models.ImageField(upload_to="capas", null=True, blank=True, default=None)
    banda = models.ForeignKey(Banda, on_delete = models.CASCADE, related_name = 'albuns')

    def __str__(self):
        return f'{self.banda} - {self.titulo}'


class Musica (models.Model):
    titulo = models.CharField(max_length = 100)
    duracao = models.CharField(max_length = 10 , verbose_name = 'Duração', default = "0")
    link_spotify = models.URLField(max_length = 200, null = True, blank=True)
    banda = models.ForeignKey(Banda, on_delete = models.CASCADE, related_name = 'musicas')
    album = models.ForeignKey(Album, on_delete = models.CASCADE, related_name = 'musicas')
    letra = models.TextField(default='', null=True, blank=True)

    def __str__(self):
        return f'{self.banda} - {self.titulo}'

bandas/forms.py
from django import forms    # formulários Django
from .models import Banda
from .models import Musica

class BandaForm(forms.ModelForm):
  class Meta:
    model = Banda        # classe para a qual é o formulário
    fields = '__all__'   # inclui no form todos os campos da classe.

    help_texts = {
            'nome': 'Insira o nome da banda.',
            'ano_criacao': 'Insira o ano de criação da banda.',
            'biografia': 'Insira uma breve biografia da banda.',
            'nacionalidade': 'Insira a nacionalidade da banda.',
            'descricao': 'Insira a descrição da banda.',
            'foto': 'Insira uma foto da banda'

        }

class MusicaForm(forms.ModelForm):
  class Meta:
    model = Musica        # classe para a qual é o formulário
    fields = '__all__'   # inclui no form todos os campos da classe.

bandas/views.py
# bandas/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import *
from .models import Musica
from .models import Banda
from .models import Album
from .forms import BandaForm
from .forms import MusicaForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def index_view(request):
    context = {
        'bandas': Banda.objects.all().order_by('nome'),
    }
    return render(request, "bandas/index.html", context)

def banda_view(request, banda_id):
    context = {
        'banda': Banda.objects.get(id=banda_id)
    }
    return render(request, "bandas/banda.html", context)

def album_view(request, album_id):
    context = {
        'album': Album.objects.get(id=album_id)
    }
    return render(request, "bandas/album.html", context)

def musica_view(request, musica_id):
    context = {
        'musica': Musica.objects.get(id=musica_id)
    }
    return render(request, "bandas/musica.html", context)



@login_required
def nova_banda_view(request):

    form = BandaForm(request.POST or None, request.FILES)      # form é uma instancia de BandaForm, request.FILES deve ser incluido se forem enviados ficheiros ou imagens


    if form.is_valid():
        form.save()
        return redirect('bandas:bandas_index')

    context = {'form': form}
    return render(request, 'bandas/nova_banda.html', context)

@login_required
def edita_banda_view(request, banda_id):
    banda = Banda.objects.get(id=banda_id)

    if request.POST:
        form = BandaForm(request.POST or None, request.FILES, instance=banda)
        if form.is_valid():
            form.save()
            return redirect('bandas:bandas_index')
    else:
        form = BandaForm(instance=banda)  # cria formulário com dados da instância

    context = {'form': form, 'banda':banda}
    return render(request, 'bandas/edita_banda.html', context)

@login_required
def apaga_banda_view(request, banda_id):
    banda = Banda.objects.get(id=banda_id)
    banda.delete()
    return redirect('bandas:bandas_index')



@login_required
def nova_musica_view(request):

    form = MusicaForm(request.POST or None)      # form é uma instancia de MusicaForm


    if form.is_valid():
        form.save()
        return redirect('bandas:bandas_index')

    context = {'form': form}
    return render(request, 'bandas/nova_musica.html', context)

@login_required
def edita_musica_view(request, musica_id):
    musica = Musica.objects.get(id=musica_id)
    album_id = musica.album.id

    if request.POST:
        form = MusicaForm(request.POST or None, instance = musica) # Passa a instância da música existente
        if form.is_valid():
            form.save()
            return redirect('bandas:album',album_id=album_id)
    else:
        form = MusicaForm(instance=musica)  # cria formulário com dados da instância

    context = {'form': form, 'musica': musica}
    return render(request, 'bandas/edita_musica.html', context)

@login_required
def apaga_musica_view(request, musica_id):
    musica = Musica.objects.get(id=musica_id)
    album_id = musica.album.id
    musica.delete()
    return redirect('bandas:album',album_id=album_id)

bandas/templates/bandas/album.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <nav>
        <a href="{% url 'bandas:banda' album.banda.id %}"><Button>{{ album.banda.nome }}</Button></a>
    </nav>
    <h3>{{ album }}</h3>
    <img src='{{ album.capa.url}}' width="150px">


    <p>Músicas:</p>
    <ul>
    {% for musica in album.musicas.all %}
        <li>
            <a href="{% url 'bandas:musica' musica.id %}">{{ musica.titulo }}
            {% if musica.letra %}
                <i class="fa-solid fa-music"></i>
            {% endif %}
            </a>

            {% if request.user.is_authenticated %}
                    <a href="{% url 'bandas:edita_musica' musica.id %}">
                        <button>Editar informação da música</button>
                    </a>
                    <a href="{% url 'bandas:apaga_musica' musica.id %}">
                        <button>Apaga música</button>
                    </a>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
    {% if request.user.is_authenticated %}
        <a href="{% url 'bandas:nova_musica' %}">
            <button>Inserir nova Musica</button>
        </a>
    {% endif %}


{% endblock %}

bandas/templates/bandas/banda.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>{{ banda }}</h3>

    <p> Nacionalidade: {{ banda.nacionalidade }}</p>
    <p> Ano de criação: {{ banda.ano_criacao }}</p>

    <p>Albúns:</p>
    <ul>
    {% for album in banda.albuns.all %}
        <li>
            <a href="{% url 'bandas:album' album.id %}">{{ album.titulo }}</a>
        </li>
    {% endfor %}
    </ul>


{% endblock %}

bandas/templates/bandas/edita_banda.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>Edita Banda</h3>

    <form action="{% url 'bandas:edita_banda' banda.id %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>

{% endblock %}

bandas/templates/bandas/edita_musica.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>Edita Música</h3>

    <form action="{% url 'bandas:edita_musica' musica.id %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>

{% endblock %}

bandas/templates/bandas/index.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <p>Existem {{ bandas|length }} bandas:</p>
    <ul>
    {% for banda in bandas %}
        <li>
            <a href="{% url 'bandas:banda' banda.id %}">{{ banda }} </a>

                {% if request.user.is_authenticated %}
                    <a href="{% url 'bandas:edita_banda' banda.id %}">
                        <button>Editar informação da Banda</button>
                    </a>
                {% endif %}

                {% if request.user.is_authenticated %}
                    <a href="{% url 'bandas:apaga_banda' banda.id %}">
                        <button>Apaga banda</button>
                    </a>
                {% endif %}
        </li>
    {% endfor %}
    </ul>
    {% if request.user.is_authenticated %}
        <a href="{% url 'bandas:nova_banda' %}">
            <button>Inserir nova Banda</button>
        </a>
    {% endif %}
{% endblock %}

bandas/templates/bandas/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bandas</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bandas/estilos.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Reddit+Mono:wght@200..900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/feef2720be.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="grid">
        <header>
            <h1>Bandas <i class="fa-solid fa-music"></i></h1>
        </header>

        <nav>
            <a href="{% url 'portfolio:index' %}"><button class="importante">Inicio</button></a>
            <a href="{% url 'bandas:bandas_index' %}"><button class="importante">Bandas</button></a>
            {% if request.user.is_authenticated %}
                Username: {{ request.user.username }}
                <a href="{% url 'autenticacao:logout' %}"><button class="importante">Logout</button></a>
            {% else %}
                <a href="{% url 'autenticacao:login' %}"><button class="importante">Login</button></a>
            {% endif %}
        </nav>

        <main>
            {% block content %}
            {% endblock %}
        </main>

        <footer>
            <p>Website by Miguel</p>
        </footer>
    </div>
</body>
</html>

bandas/templates/bandas/musica.html
{% extends 'bandas/layout.html' %}



{% block content %}
    <nav>
        <a href="{% url 'bandas:album' musica.album.id %}"><Button>{{ musica.album.titulo }}</Button></a>
    </nav>
    <h3>{{ musica }}</h3>

    <p> Duração: {{ musica.duracao }}</p>



{% endblock %}

bandas/templates/bandas/nova_banda.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>Nova Banda</h3>

    <form action="" method="post" enctype='multipart/form-data'>
    <!-- enctype deve ser definido se houver submissão de ficheiros ou imagens -->

      {% csrf_token %}   <!-- obrigatório nos forms Django -->
      <table>
          {{ form }}   <!-- insere input para cada atributo da classe Autor, numa tabela -->
      </table>
      <input type="submit" value="Criar banda">

    </form>

{% endblock %}

bandas/templates/bandas/nova_musica.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>Nova Música</h3>

    <form action="" method="post" enctype='multipart/form-data'>
    <!-- enctype deve ser definido se houver submissão de ficheiros ou imagens -->

      {% csrf_token %}   <!-- obrigatório nos forms Django -->
      <table>
          {{ form }}   <!-- insere input para cada atributo da classe Musica, numa tabela -->
      </table>
      <input type="submit" value="Criar musica">

    </form>

{% endblock %}