ensinosuperior/urls.py
from django.urls import path

from . import views

app_name = 'ensinosuperior'

urlpatterns = [
    path('', views.index_view, name="ensinosuperior_index"),
    path('disciplina/<int:disciplina_id>/', views.disciplina_view, name="disciplina"),
    path('projeto/<int:projeto_id>/', views.projeto_view, name="projeto"),

]

meteo/urls.py
from django.urls import path
from . import views

app_name = 'meteo'

urlpatterns = [
    path('lisboa/', views.tempo_lisboa_view, name='tempo_lisboa'),

]

portfolio/urls.py
from django.urls import path

from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.index_view, name="index"),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('latintext/', include('latintext.urls')),
    path('bandas/', include('bandas.urls')),
    path('praias/', include('praias.urls')),
    path('ensinosuperior/', include('ensinosuperior.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('', include('portfolio.urls')),
    path('meteo/', include('meteo.urls')),

]

ensinosuperior/models.py
from django.db import models

# Create your models here.

class Curso (models.Model):
    nome = models.CharField(max_length = 100)
    apresentacao = models.TextField(blank = True, null = True)
    objetivos = models.TextField(blank = True, null = True)
    competencias = models.TextField(blank = True, null = True)
    horas_contacto_total = models.CharField(max_length = 10)
    ects = models.IntegerField()

    def __str__(self):
        return f'{self.nome}'


class AreaCientifica (models.Model):
    nome = models.CharField(max_length = 100)

    def __str__(self):
        return f'{self.nome}'


class Disciplina (models.Model):
    nome = models.CharField(max_length = 100)
    ramo = models.CharField(max_length = 100)
    ano =  models.IntegerField()
    semestre = models.CharField(max_length = 15)
    ects = models.IntegerField()
    horas_contacto = models.CharField(max_length = 10)
    curricularIUnitReadableCode = models.CharField(max_length = 100)
    cursos = models.ManyToManyField(Curso, related_name = 'disciplinas')
    area_cientifica = models.ForeignKey(AreaCientifica, on_delete = models.CASCADE, related_name = 'disciplinas', null = True)

    def __str__(self):
        return f'{self.nome}'

class Projeto (models.Model):
    nome = models.CharField(max_length = 100)
    descricao = models.TextField(blank = True, null = True)
    conceitos_aplicados = models.TextField(blank = True, null = True)
    link_video = models.URLField(max_length = 200, null = True)
    link_github = models.URLField(max_length = 200, null = True)
    disciplina = models.OneToOneField(Disciplina, on_delete=models.CASCADE, related_name = 'projeto',null = True)

    def __str__(self):
        return f'{self.nome}'


class LinguagemProgramacao (models.Model):
    nome = models.CharField(max_length = 100)
    descricao = models.TextField(blank = True, null = True)
    projetos = models.ManyToManyField(Projeto ,related_name = 'linguagem_programacao')

    def __str__(self):
        return f'{self.nome}'


class Docente (models.Model):
    nome = models.CharField(max_length = 100)
    email = models.CharField(max_length = 100, null=True)
    disciplinas = models.ManyToManyField(Disciplina, related_name = 'docentes')

ensinosuperior/views.py
# ensinosuperior/views.py
from django.shortcuts import render
from .models import *
from .models import Curso
from .models import AreaCientifica
from .models import Disciplina
from .models import Projeto
from .models import LinguagemProgramacao
# Create your views here.

def index_view(request):
    context = {
        'curso': Curso.objects.get(nome = 'Engenharia Informática'),
    }
    return render(request, "ensinosuperior/index.html", context)

def disciplina_view(request, disciplina_id):
    context = {
        'disciplina': Disciplina.objects.get(id=disciplina_id)
    }
    return render(request, "ensinosuperior/disciplina.html", context)

def projeto_view(request, projeto_id):
    context = {
        'projeto': Projeto.objects.get(id=projeto_id)
    }
    return render(request, "ensinosuperior/projeto.html", context)

ensinosuperior/templates/ensinosuperior/disciplina.html
{% extends 'ensinosuperior/layout.html' %}

{% block content %}

    <h3>{{ disciplina }}</h3>
    <h4>Ramo</h4>
    <p>{{disciplina.ramo}}</p>
    <h4>Ano</h4>
    <p>{{disciplina.ano}}</p>
    <h4>Semestre</h4>
    <p>{{disciplina.semestre}}</p>
    <h4>ECTS</h4>
    <p>{{disciplina.ects}}</p>
    <h4>Horas de Contacto</h4>
    <p>{{disciplina.horas_contacto}}</p>
    <h4>Curricular Unit Readable Code</h4>
    <p>{{disciplina.curricularIUnitReadableCode}}</p>
    <h4>Area Cientifica</h4>
    <p>{{disciplina.area_cientifica}}</p>


    <h4>Projeto</h4>
    <ul>
    {% if disciplina.projeto %}
        <ul>
            <li>
                <a href="{% url 'ensinosuperior:projeto' disciplina.projeto.id %}">{{ disciplina.projeto }}</a>
            </li>
        </ul>
    {% else %}
        <p>Nenhum projeto associado a esta disciplina.</p>
    {% endif %}
    </ul>


{% endblock %}

ensinosuperior/templates/ensinosuperior/index.html
{% extends 'ensinosuperior/layout.html' %}

{% block content %}
    <ul>

    <h1>{{curso.nome}}</h1>

    <h3>Apresentação</h3>
    <p>{{curso.apresentacao}}</p>

    <h3>Objetivos</h3>
    <p>{{curso.objetivos}}</p>

    <h3>Competencias</h3>
    <p>{{curso.competencias}}</p>

    <h3>Horas de Contacto</h3>
    <p>{{curso.horas_contacto_total}}</p>

    <h3>ECTS</h3>
    <p>{{curso.ects}}</p>

    <h2>Disciplinas</h2>
    {% for disciplina in curso.disciplinas.all %}
        <li>
            <a href="{% url 'ensinosuperior:disciplina' disciplina.id %}">{{ disciplina }}</a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

ensinosuperior/templates/ensinosuperior/layout.html
<html>
<head>
    <meta charset="UTF-8">
    <title>Curso</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'ensinosuperior/estilos.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Reddit+Mono:wght@200..900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/feef2720be.js" crossorigin="anonymous"></script>
</head>
    <body>
        <header>
            <h1>Curso</h1>
            <a href="{% url 'portfolio:index' %}"><button class="importante">Inicio</button></a>
            <a href="{% url 'ensinosuperior:ensinosuperior_index' %}"><button class="importante">Curso</button></a>
        </header>

        <main>

            {% block content %}
            {% endblock %}

        </main>

        <footer>
            <p>Website by Miguel</p>
        </footer>
    </body>
</html>

ensinosuperior/templates/ensinosuperior/projeto.html
{% extends 'ensinosuperior/layout.html' %}

{% block content %}
    <nav>
        <a href="{% url 'ensinosuperior:disciplina' projeto.disciplina.id %}"><Button>{{ projeto.disciplina }}</Button></a>
    </nav>
    <h2>{{projeto.disciplina}}</h2>
    <h3>{{ projeto }}</h3>

    <p>{{projeto.descricao}}</p>
    <h5>Conceitos aplicados</h5>
    <p>{{projeto.conceitos_aplicados}}</p>



    <a href="{{projeto.link_video}}">Video no youtube</a>
    <p></p>
    <a href="{{projeto.link_github}}">Github</a>



{% endblock %}